### ISSUE TITLE
Nodejs Payment

### ISSUE THREAD

**Issue by katp4** [amzn/login-and-pay-with-amazon-sdk-samples#3]
Hello,

Are there any plans of adding a Node.js payment example? Currently there is only a login one whereas the other languages contain checkout code as well.

Thank you

**Comment by samir-khoja** [comment]
Hey, 

Yes, I have a Node.js example available. Unfortunately, it has not yet been added to this repository. It should be added in the near future. Feel free to email me directly and I will be happy to share the sample code with you.
