### ISSUE TITLE
How to Collect Payment?

### ISSUE THREAD

**Issue by webprogrammierer** [amzn/login-and-pay-with-amazon-sdk-samples#6]
Hello,

I installed the php version of "login-and-pay-with-amazon-sdk-samples" (SampleCartDemo > OneTimePayments) and it seems to work fine (sandbox).

I can see the transactions in my amazony pay account (orders):

Total: 19.95
Charged: 0.00

All transactions are successfull but no real charge has be done. 
I have to click on "Collect Payment" at any transaction in order to charge/get the amout from customer. But I do not want to do this manually.

How can the php code be changed/extended so that all transactions are charged/collected directly within the php code (e.g. in ConfirmPaymentAndAuthorize.php)?

Thank you.

**Comment by bjguillot** [comment]
There are several different workflows that you could use.

The simplest to implement is to set the $requestParameters['capture_now'] line in Apicalls/ConfirmAndAuthorize.php to true (instead of false).

Setting capture_now to true will attempt to collect payment at the same time as the authorization.  This is generally only recommended for digital goods.  The best practice for physical goods is to perform the capture of funds immediately prior to shipping the goods to the buyer.

Try that and let us know if it works.

**Comment by tarishah** [comment]
As per bjguillot's comment, if you are selling physical goods, you may want to capture funds prior to shipping the goods. Below code sample is something you can add on your end.
This demonstrates Auth and Capture call-

// If the API call was a success make the Authorize API call
if($client->success)
{
    $requestParameters['authorization_amount'] = '1.00';
    $requestParameters['authorization_reference_id'] = 'Your Unique Reference Id';
    $requestParameters['seller_authorization_note'] = 'Authorizing payment';
    $requestParameters['transaction_timeout'] = 0;

    $response = $client->authorize($requestParameters);
    $responsearray['authorize'] = json_decode($response->toJson());
}

// If the Authorize API call was a success, make the Capture API call when you are ready to capture for the order (for example when the order has been dispatched)
if($client->success)
{
    $requestParameters['amazon_authorization_id'] = 'Parse the Authorize Response for this id';
    $requestParameters['capture_amount'] = '1.00';
    $requestParameters['currency_code'] = 'USD';
    $requestParameters['capture_reference_id'] = 'Your Unique Reference Id';

    $response = $client->capture($requestParameters);
    $responsearray['capture'] = json_decode($response->toJson());
}

You can find the above code here- https://amzn.github.io/login-and-pay-with-amazon-sdk-samples/simple.html

Steps- Please login with your test account and click place order. Scroll down to see the sample API calls in PHP.

**Comment by webprogrammierer** [comment]
Thank you.
If have set capture_now to true and now it works fine.
And yes, I have digital goods.

**Comment by bjguillot** [comment]
OK, great.  I'll go ahead and close your issue then.  Thanks for using Amazon Pay.

**Comment by webprogrammierer** [comment]
One additional question:

After capture has be done I want to close the order. But I can't find any CloseOrderReference() function call in your example code "SampleCartDemo" - "OneTimePayments".

Can you tell me where in the source code of your example code and how to close the order?
Thank you.

**Comment by bjguillot** [comment]
Below I have pasted some PHP example code to close an order reference.  It assumes that your $client is ready and that $orderReference has your S0n-xxx-xxx or P0n-xxx-xxx order reference.

        $configArray = [
                'amazon_order_reference_id' => $orderReference,
                'closure_reason' => 'For Merchant use only, never shown to buyer'];
        $response = $client->closeOrderReference($configArray)->toArray();
        if ($response['ResponseStatus'] != 200)
                print "Error Occurred!\n";
        else
                print "Order Reference Closed\n";

**Comment by webprogrammierer** [comment]
Thank you.
Where can I put this code into? ConfirmPaymentAndAuthorize.php?
