### ISSUE TITLE
Omit shipping address

### ISSUE THREAD

**Issue by webprogrammierer** [amzn/login-and-pay-with-amazon-sdk-samples#7]
For digital goods there is no shipping address necessary.

Is it possible to omit shipping address?

After login the customer should only select the payment method (VISA, Mastercard, ...) but NOT the shipping address (the shipping address should not be shown to the customer).

How can I do this?
Thank you.

**Comment by bjguillot** [comment]
In the SetPaymentDetails.php file in the OneTimePayments example, you can remove the block of code including and between the lines:

    new OffAmazonPayments.Widgets.AddressBook({
    ....
    }).bind("addressBookWidgetDiv");

You can also remove this line:

    <div id="addressBookWidgetDiv" style="width:400px; height:240px; display:inline-block;"></div>

That will remove the widget from your screen.  You may need to do some additional code on the backend to remove references to shipping address, including no longer needing to pass the AddressConsentToken (or AccessToken) to the backend.

Try these things and let us know if you have any questions.

**Comment by webprogrammierer** [comment]
You want to remove all these lines of code:

```
        new OffAmazonPayments.Widgets.AddressBook({
            sellerId: "A2HPDMHZ31Z2DD",
            onOrderReferenceCreate: function (orderReference) {

                /* make a call to the back-end that will set order reference details
                 * and get order reference details. This will set the order total
                 * to 19.95 and return order reference details.
                 *
                 * Get the AddressConsentToken to be sent to the API call
                 */
               var access_token = "";

                $.post("Apicalls/GetDetails.php", {
                    orderReferenceId: orderReference.getAmazonOrderReferenceId(),
                    addressConsentToken: access_token,
                }).done(function (data) {
                   $("#get_details_response").html(data);
                });
            },
            onAddressSelect: function (orderReference) {
            },
            design: {
                designMode: 'responsive'
            },
            onError: function (error) {
                // your error handling code
            }
        }).bind("addressBookWidgetDiv");

```

So the  `$.post("Apicalls/GetDetails.php", {` is also removed and then nothing works anymore.

There are so many problems here. Why is nobody here who can support people who want to implement amazon pay?

**Comment by bjguillot** [comment]
OK, I looked into and see my omission.  

The onOrderReferenceCreate callback needs to be moved to the Wallet Widget, i.e., so this part:

            onOrderReferenceCreate: function (orderReference) {

                /* make a call to the back-end that will set order reference details
                 * and get order reference details. This will set the order total
                 * to 19.95 and return order reference details.
                 *
                 * Get the AddressConsentToken to be sent to the API call
                 */
               var access_token = "";

                $.post("Apicalls/GetDetails.php", {
                    orderReferenceId: orderReference.getAmazonOrderReferenceId(),
                    addressConsentToken: access_token,
                }).done(function (data) {
                   $("#get_details_response").html(data);
                });
            },

Needs to be inserted after the lines
   
     new OffAmazonPayments.Widgets.Wallet({
            sellerId: "SELLER_ID",

You only want to have one widget that uses the onOrderReferenceCreate callback, and since we removed the AddressBook widget, we need to move it to the Wallet widget.

Sorry for not mentioning that originally.

There are some other optimizations you can do for digital only goods, such as removing the payments:shipping_address portion of the scope from the index.html file.

**Comment by webprogrammierer** [comment]
Thank you. I have already find that out by myself.
